---
- name: Install Apache.
  package: # quiet by default
    name: "{{ apache_package }}"
    state: present
    
- name: Copy test config file.
  copy:
    src: files/test.conf
    dest: "{{ apache_config_dir }}/test.conf"
  notify: restart apache # if a change then call handler

- name: Ensure Apache started and configure it to run at boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true